;; -*- mode: eask; lexical-binding: t -*-

(package "cat"
         "1.0.0"
         "View files with syntax highlighting")

(website-url "https://github.com/emacs-eine/cat")
(keywords "convenience")

(package-file "cat.el")
(files "bin")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "26.1")
(depends-on "e2ansi")
(depends-on "commander")
(depends-on "msgu")
